### ISSUE TITLE
James Skinner Logo

### ISSUE THREAD

**Issue by JSkins** [JSkins/Portfolio#2]
Optimised Logo is not showing on page

**Comment by PrenSJ2** [comment]
![image](https://github.com/JSkins/Portfolio/assets/70067036/b0b57464-2c58-4d1f-9ee2-801c540c7526)


Changed logos to be svg icons so that they are loaded in the most efficient way

**Comment by PrenSJ2** [comment]
- tip when possible use the 'Icon' widget with the SVG file rather than a png or webp in an image
